server:
  port: 5005

spring:
  application:
    name: comment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/task_comment_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

api:
  prefix: api/v1